apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: kubeserve
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: {{ .Release.Name }}
        ports:
        - containerPort: 80
        env:
        - name: sahi
          valueFrom:
            configMapKeyRef:
              name: v1
              key: key1
