apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  drink: "Mango"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trackerdev
      #release: {{ .Release.Name }}
      #tier: frontend
  template:
    metadata:
      name: kubeserve
      labels:
        app: trackerdev
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ .Release.Name }}
        ports:
        - containerPort: 80
        env:
        - name: sahi
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: drink
